# TODO: Move to database

RIVERS = [
        ["Wisła"],
        ["Odra", "Odra Południowa", "Odra Zachodnia/Westoder", "Odra Zachodnia", "Odra Wschodnia", "Stara Odra", "Oder/Odra", "Odra/Oder","Odra Północna", "Westoder - Odra Zachodnia"],
        ["Warta"],
        ["Bug","Bug / Заходні Буг","Bug / Західний Буг"],
        ["Narew"],
        ["San"],
        ["Noteć"],
        ["Pilica"],
        ["Wieprz"],
        ["Bóbr"],
        ["Wkra"],
        ["Dunajec"],
        ["Brda"],
        ["Prosna"],
        ["Drwęca"],
        ["Wisłok"],
        ["Nysa Łużycka"],
        ["Wda"],
        ["Łyna"],
        ["Drawa"],
        ["Nysa Kłodzka"],
        ["Poprad"],
        ["Rega"],
        ["Bzura"],
        ["Biebrza"],
        ["Wisłoka"],
        ["Obra"],
        ["Nida"],
        ["Wierzyca"],
        ["Orzyc"],
        ["Gwda"],
        ["Czarna Hańcza"],
        ["Wieprza"],
        ["Parsęta"],
        ["Barycz"],
        ["Kamienna"],
        ["Słupia"],
        ["Raba"],
        ["Mała Panew"],
        ["Baryczy"],
        ["Kwisa"],
        ["Ina"],
        ["Liwiec"],
        ["Krzna"],
        ["Wełna"],
        ["Łeba"],
        ["Skrwa"],
        ["Tanew"],
        ["Omulew"],
        ["Liwa"],
        ["Supraśl"],
        ["Widawa"],
        ["Biała"],
        ["Nurzec"],
        ["Olza"],
        ["Radomka"],
        ["Rawka"],
        ["Skawa"],
        ["Bystrzyca"],
        ["Strwiąż"],
        ["Oława"],
        ["Soła"],
        ["Czarna"],
        ["Przemsza"],
        ["Wąglanka"],
        ["Mała Wisła"],
        ["Ślęza"],
        ["Kaczawa"],
        ["Pisa"],
        ["Łęg"],
        ["Szreniawa"],
        ["Ropa"],
        ["Grabia"],
        ["Stobrawa"],
        ["Drwinka"],
        ["Jasiołka"],
        ["Osobłoga"],
        ["Mierzawa"],
        ["Czarna Nida"],
        ["Mroga"],
        ["Biała Przemsza"],
        ["Brenna"],
        ["Brynica"],
        ["Łososina"],
        ["Bukowa"],
        ["Dłubnia"],
        ["Oleśnica"],
        ["Breń"],
        ["Pszczynka"],
        ["Uherka"],
        ["Rudawa"],
        ["Prądnik"],
        ["Skawinka"],
        ["Kamienica"],
        ["Gostynia"],
        ["Włodawka"],
        ["Koszarawa"],
        ["Regulka"],
        ["Wieprzówka"],
        ["Żylica"],
        ["Wilga"],
        ["Stryszawka"],
    ]

ZOOM_LEVELS = [
    {"max_zoom": 2, "tolerance": 1, "river_count": 1},
    {"max_zoom": 3, "tolerance": 1, "river_count": 3},
    {"max_zoom": 4, "tolerance": 1, "river_count": 10},
    {"max_zoom": 5, "tolerance": 0.1, "river_count": 15},
    {"max_zoom": 6, "tolerance": 0.01, "river_count": len(RIVERS)},
    {"max_zoom": 7, "tolerance": 0.01, "river_count": len(RIVERS)},
    {"max_zoom": 8, "tolerance": 0.01, "river_count": len(RIVERS)},
    {"max_zoom": 10, "tolerance": 0.001, "river_count": None},
    {"max_zoom": 13, "tolerance": 0.0001, "river_count": None},
    {"max_zoom": float('inf'), "tolerance": 0, "river_count": None},
]

