# Generated by Django 5.1.2 on 2024-10-27 16:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiverSegment',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('flow_direction', models.CharField(blank=True, choices=[('upstream', 'Upstream'), ('downstream', 'Downstream')], max_length=20, null=True)),
                ('flow_rate', models.FloatField(blank=True, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
            options={
                'indexes': [models.Index(fields=['geometry'], name='idx_river_segment_geometry', opclasses=['gist_geometry_ops_2d'])],
                'constraints': [models.CheckConstraint(condition=models.Q(('flow_rate__gt', 0), ('flow_rate__isnull', True), _connector='OR'), name='valid_flow_rate')],
            },
        ),
    ]
